/**
 * Token generator.
 *
 * DESIGN.md is the single source of truth. This script reads the `palette`
 * block from its YAML front matter, runs it through lib/palette/engine.ts, and
 * writes two things:
 *
 *   1. app/tokens.css              — the CSS custom properties the app consumes
 *   2. DESIGN.md's GENERATED block — a read-only mirror of the derived colours,
 *                                    so DESIGN.md answers colour questions alone
 *
 * Usage:
 *   pnpm gen:tokens            write both outputs
 *   pnpm gen:tokens --check    exit 1 if either has drifted (pre-commit / CI)
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join, relative } from "node:path"

import { toCss, generateThemes, type PaletteConfig } from "../lib/palette/engine.ts"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")
const designPath = join(root, "DESIGN.md")
const cssPath = join(root, "app", "tokens.css")

const check = process.argv.includes("--check")
const rel = (p: string) => relative(root, p)

// --- read the palette config out of DESIGN.md's front matter ----------------
// Deliberately a narrow reader rather than a YAML dependency: the palette is
// four numbers, and a strict regex fails loudly if one goes missing.
const PALETTE_KEYS = [
  "neutralHue",
  "neutralChroma",
  "accentHue",
  "contrast",
] as const

function readPaletteConfig(source: string): PaletteConfig {
  const block = source.match(/^palette:\s*$\n((?:^[ \t]+.*$\n?)+)/m)
  if (!block) {
    throw new Error(`${rel(designPath)}: no \`palette:\` block found in the front matter`)
  }
  const cfg = {} as Record<string, number>
  for (const key of PALETTE_KEYS) {
    const hit = block[1].match(new RegExp(`^\\s+${key}:\\s*(-?[0-9.]+)`, "m"))
    if (!hit) {
      throw new Error(`${rel(designPath)}: \`palette.${key}\` is missing`)
    }
    const value = Number(hit[1])
    if (!Number.isFinite(value)) {
      throw new Error(`${rel(designPath)}: \`palette.${key}\` is not a number: ${hit[1]}`)
    }
    cfg[key] = value
  }
  return cfg as PaletteConfig
}

// --- render the GENERATED mirror block --------------------------------------
const START = "# >>> GENERATED BY pnpm gen:tokens — DO NOT EDIT BY HAND"
const END = "# <<< END GENERATED"

/** Colour tokens only — `radius` is authored in `rounded.base`, not derived. */
const isColour = ([key]: [string, string]) => key !== "radius"

function yamlBlock(name: string, tokens: Record<string, string>): string {
  const entries = Object.entries(tokens).filter(isColour)
  const lines = entries.map(([k, v]) => `  ${k}: "${v}"`)
  return [`${name}:`, ...lines].join("\n")
}

function renderMirror(cfg: PaletteConfig): string {
  const { light, dark } = generateThemes(cfg)
  return [
    START,
    "# A read-only mirror of what the engine derives from `palette` above, so this",
    "# file answers colour questions on its own. `pnpm gen:tokens --check` fails if",
    "# these have drifted. To change a colour, change `palette` and regenerate.",
    yamlBlock("colors", light),
    "",
    yamlBlock('"colors-dark"', dark),
    END,
  ].join("\n")
}

function replaceMirror(source: string, mirror: string): string {
  const start = source.indexOf(START)
  const end = source.indexOf(END)
  if (start === -1 || end === -1) {
    throw new Error(
      `${rel(designPath)}: GENERATED markers not found — expected "${START}" … "${END}"`
    )
  }
  return source.slice(0, start) + mirror + source.slice(end + END.length)
}

// --- run --------------------------------------------------------------------
const design = readFileSync(designPath, "utf8")

let cfg: PaletteConfig
try {
  cfg = readPaletteConfig(design)
} catch (error) {
  console.error(`✗ ${error instanceof Error ? error.message : error}`)
  process.exit(1)
}

const nextCss = toCss(cfg)
const nextDesign = replaceMirror(design, renderMirror(cfg))

const outputs: { path: string; next: string; drift: string }[] = [
  { path: cssPath, next: nextCss, drift: "does not match DESIGN.md's palette" },
  { path: designPath, next: nextDesign, drift: "GENERATED colour block is stale" },
]

if (check) {
  const drifted = outputs.filter(({ path, next }) => readFileSync(path, "utf8") !== next)
  if (drifted.length) {
    for (const { path, drift } of drifted) {
      console.error(`✗ ${rel(path)}: ${drift}`)
    }
    console.error("  run: pnpm gen:tokens")
    process.exit(1)
  }
  console.log("✓ tokens are in sync with DESIGN.md")
} else {
  for (const { path, next } of outputs) {
    writeFileSync(path, next)
    console.log(`✓ wrote ${rel(path)}`)
  }
}

console.log(
  `  palette: neutralHue=${cfg.neutralHue} neutralChroma=${cfg.neutralChroma} accentHue=${cfg.accentHue} contrast=${cfg.contrast}`
)
